Add packaging step to verify package installation

diff --git a/support/docker-builds/images/fedora-commons/Dockerfile.in b/support/docker-builds/images/fedora-commons/Dockerfile.in
--- a/support/docker-builds/images/fedora-commons/Dockerfile.in
+++ b/support/docker-builds/images/fedora-commons/Dockerfile.in
@@ -1,4 +1,18 @@
 cp "$( dirname "$BASH_SOURCE")/configuration-${FEDORA_VERSION}.cmake" "$PWD"
+cat >rpm-package-checker.sh <<'EOF'
+#!/bin/bash
+PACKAGE="$1"
+
+if ! [[ -r "$PACKAGE" ]]; then
+    echo "Unable to find package to test: $PACKAGE" >&2
+    exit 1
+fi
+echo "**** Testing installation for $PACKAGE"
+yum install -y "$PACKAGE"
+EOF
+
+chmod a+x rpm-package-checker.sh
+ 
 
 cat <<EOF
 FROM ${FEDORA_BASE_IMAGE}
@@ -22,6 +36,8 @@ EOF
 
 cat <<EOF
 COPY configuration-${FEDORA_VERSION}.cmake /
+COPY rpm-package-checker.sh /usr/local/bin/
 ENV CMAKE_EXTRA_OPTIONS -DCMAKE_INCLUDE_EXT_FILE=/configuration-${FEDORA_VERSION}.cmake -DCPACK_GENERATOR=RPM
+ENV TEST_PACKAGE_CMD="/usr/local/bin/rpm-package-checker.sh"
 EOF
 
