Add new ASI sdk

diff --git a/support/raspberry-ubuntu-16.04-build/prepare-root b/support/raspberry-ubuntu-16.04-build/prepare-root
--- a/support/raspberry-ubuntu-16.04-build/prepare-root
+++ b/support/raspberry-ubuntu-16.04-build/prepare-root
@@ -1,9 +1,35 @@
 #!/bin/bash
 RELEASE="xenial"
 . commons
-apt-get install -y qemu-user-static binfmt-support debootstrap
+
+if ! hash lsb_release >/dev/null 2>&1; then
+	echo "lsb_release missing: not able to know distribution details" >&2
+	exit 1
+fi
+
+
+if ! hash update-binfmts >/dev/null 2>&1 || ! hash qemu-arm-static; then
+	case "$( lsb_release -is )" in
+		"Arch")
+			AUR_MANAGER="${AUR_MANAGER:-packer}" # overwrite with env variable if you want to use another compatible package, like yaourt, etc
+			sudo -u $SUDO_USER $AUR_MANAGER -S qemu-user-static binfmt-support
+			;;
+		"Ubuntu")
+			apt-get install -y qemu-user-static binfmt-support debootstrap
+  			;;
+	esac
+fi
+
 update-binfmts --enable
-[[ -r "$root"/usr/bin/qemu-arm-static ]] || qemu-debootstrap --arch armhf $RELEASE "$root" http://ports.ubuntu.com/ && cp -av /usr/bin/qemu-arm-static raspberry-root/usr/bin
+alias qemu-debootstrap=debootstrap
+if ! [[ -r "$root"/usr/bin/qemu-arm-static ]]; then
+       debootstrap --foreign --arch armhf $RELEASE "$root" http://ports.ubuntu.com/
+       cp -av "$( which qemu-arm-static )" raspberry-root/usr/bin
+       DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
+	        LC_ALL=C LANGUAGE=C LANG=C chroot raspberry-root/ /debootstrap/debootstrap --second-stage
+       DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
+	        LC_ALL=C LANGUAGE=C LANG=C chroot raspberry-root dpkg --configure -a
+fi
 cat >"$root"/etc/apt/sources.list <<EOF
 deb http://ports.ubuntu.com/ubuntu-ports xenial main restricted universe multiverse
 EOF
