Major build system update:
 - Remove old images (unsupported ubuntu versions)
 - Use MXE script to dynamically find and install dependencies
 - Fix compilation on broken targets
 - Use docker hub as base image for arm targets

diff --git a/support/docker-builds/images/ubuntu-18.04-arm/prepare-image b/support/docker-builds/images/ubuntu-18.04-arm/prepare-image
--- a/support/docker-builds/images/ubuntu-18.04-arm/prepare-image
+++ b/support/docker-builds/images/ubuntu-18.04-arm/prepare-image
@@ -1,3 +1,8 @@
 #!/bin/bash
+if ! which qemu-arm-static >/dev/null 2>&1; then
+    echo "Error: unable to find qemu-arm-static in path. Please install it first" >&2
+    exit 1
+fi
+cp "$( which qemu-arm-static )" .
+PREPARATION_COMMAND="COPY qemu-arm-static /usr/bin"
 . Dockerfile.in > Dockerfile
-( cd ../ubuntu-arm-base/ && ./prepare-image artful)
